name: CI

on:
  push:
    branches:
      - main
      - dbehnke/custom
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.13]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install uv (curl installer)
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install project dependencies via uv
        run: |
          # Use uv to install from requirements.txt (uv will create/manage the venv)
          if [ -f requirements.txt ]; then
            uv install -r requirements.txt
          else
            uv install pytest
          fi

      - name: Run tests via uv
        run: |
          uv run pytest -q
